### ISSUE TITLE
Bug in FindByLoginAsync

### ISSUE THREAD

**Issue by irriss** [bordereast/aspnetcore-identity-arangodb#1]
Hi there,
Excellent job with this project.
However, I faced an issue trying to use method `UserStore.FindByLoginAsync`

It uses 
`var user = await client.DB().GetByExampleAsync<TUser>(new { logins = new { loginProvider = loginProvider, providerKey = providerKey } });`

Which does not work for at least two reasons:
1) logins is an array
2) there might be other attributes in the login so it will not match 

Any expectations for this bug to be fixed?

Thanks for great job

**Comment by agrothe** [comment]
I’ll see if I can have a look.

**Comment by agrothe** [comment]
Released new nuget package: 

`Install-Package BorderEast.ASPNetCore.Identity.ArangoDB -Version 0.2.2`

**Comment by irriss** [comment]
It works!

Thanks

**Comment by irriss** [comment]
I am trying to find a suitable index for that query https://stackoverflow.com/questions/46997849/array-index-on-arangodb
